#
# [container_item_padding] is the amount of padding space
# which will be used for packing material surrounding
# each product in a shipping container

# [shipping_price_buffer] is the percentage by which we will
# increase the realtime shipping price information
#
######
development: &non_production_settings
    admin_email: brian@parkersmithsoftware.com
    supervisor_email: brian@parkersmithsoftware.com
    blog_location: http://blog.dormbuys.com
    contact_email: brian@parkersmithsoftware.com
    dev_email: brian@parkersmithsoftware.com
    warehouse_admin_email: brian@parkersmithsoftware.com
    enc_key: abc123
    enc_salt: zxy098
    base_url: localhost:3000
    show_mini_cart: false
    max_prod_qty: 50
    shipping_settings:
        container_item_padding: 0.25
        shipping_price_buffer: 0.00
        drop_ship_alone: 15
    authorize_net:
        login_id: 3bbS2x8UZDU
        transaction_key: 38v7Y92U2BmqRdzh
    filesystem:
        local_files_path: /public/content/files/products
        web_files_path: /content/files/products
        local_labels_path: /public/content/files/shipping_labels
        web_labels_path: /content/files/shipping_labels
        local_images_path: /public/content/images/products
        web_images_path: /content/images/products
    fedex:
        auth_key: hnbs3bHzmVY0ZoIU
        auth_password: pmdizG6iI0ypnv3EW7V9Opw94 
        account_number: 510087526
        meter_number: 1223651
    ups:
        origin_number: A64V28 #1Y6809
        login: dormbuysdotcom #qmilouisville
        password: xavier01 #password
        key: 9C60A235E9C53978 #8C79BD531775B808
        testing: 1
    googleproducts:
        host: uploads.google.com
        user: dormbuys123
        pass: sellit123
    channel_advisor:
        host: partner.channeladvisor.com
        user: dormby:ftpuser@dormbuys.com
        pass: shdormby1!ad
    bingshopping:
        host: feeds.adcenter.microsoft.com
        user: dormbuys
        pass: AsO37mh|2T
        
test: 
    <<: *non_production_settings
    
production:
    <<: *non_production_settings
