class UpdateLntCategories < ActiveRecord::Migration
  def self.up
    ThirdPartyCategory.delete_all
    
    ThirdPartyCategory.create(:name => "Bathroom", :parent => "", :owner => "Linens-N-Things", :level => 1)
      ThirdPartyCategory.create(:name => "Bath Accessories", :parent => "Bathroom", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Bath Mats", :parent => "Bathroom", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Bath Towels", :parent => "Bathroom", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Laundry/Cleaning", :parent => "Bathroom", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Robes", :parent => "Bathroom", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Shower Caddy", :parent => "Bathroom", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Shower Curtains", :parent => "Bathroom", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Shower Shoes", :parent => "Bathroom", :owner => "Linens-N-Things", :level => 2)
    
    ThirdPartyCategory.create(:name => "Bedding", :parent => "", :owner => "Linens-N-Things", :level => 1)
      ThirdPartyCategory.create(:name => "Allergy Relief Bedding", :parent => "Bedding", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Bed in a Bag", :parent => "Bedding", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Bedding Accessories", :parent => "Bedding", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Blankets & Throws", :parent => "Bedding", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Comforters", :parent => "Bedding", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Dorm Bedding", :parent => "Bedding", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Down Comforters", :parent => "Bedding", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Duvet Covers", :parent => "Bedding", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Futon Covers", :parent => "Bedding", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Kid's Bedding", :parent => "Bedding", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Mattress Pads", :parent => "Bedding", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Mattress Toppers", :parent => "Bedding", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Pillow Cases", :parent => "Bedding", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Pillows", :parent => "Bedding", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Quilts", :parent => "Bedding", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Sheets", :parent => "Bedding", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Team Bedding", :parent => "Bedding", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Teen Bedding", :parent => "Bedding", :owner => "Linens-N-Things", :level => 2)
    
    ThirdPartyCategory.create(:name => "Electric Accessories", :parent => "", :owner => "Linens-N-Things", :level => 1)
      ThirdPartyCategory.create(:name => "Alarm Clocks / Clocks", :parent => "Electric Accessories", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Fans/Heaters", :parent => "Electric Accessories", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Humidifiers", :parent => "Electric Accessories", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Irons & Boards", :parent => "Electric Accessories", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Steamers", :parent => "Electric Accessories", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Sweepers", :parent => "Electric Accessories", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Vacuums", :parent => "Electric Accessories", :owner => "Linens-N-Things", :level => 2)
    
    ThirdPartyCategory.create(:name => "Furnishings", :parent => "", :owner => "Linens-N-Things", :level => 1)
      ThirdPartyCategory.create(:name => "Alarm Clocks/Clocks", :parent => "Furnishings", :owner => "Linens-N-Things", :level => 2)
        ThirdPartyCategory.create(:name => "Alarm Clocks", :parent => "Alarm Clocks/Clocks", :owner => "Linens-N-Things", :level => 3)
        ThirdPartyCategory.create(:name => "Wall Clocks", :parent => "Alarm Clocks/Clocks", :owner => "Linens-N-Things", :level => 3)
      ThirdPartyCategory.create(:name => "Bookcases/Shelving", :parent => "Furnishings", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Decorative Accessories", :parent => "Furnishings", :owner => "Linens-N-Things", :level => 2)
        ThirdPartyCategory.create(:name => "Part Stuff", :parent => "Decorative Accessories", :owner => "Linens-N-Things", :level => 3)
        ThirdPartyCategory.create(:name => "Wall and Door", :parent => "Decorative Accessories", :owner => "Linens-N-Things", :level => 3)
        ThirdPartyCategory.create(:name => "Message Boards", :parent => "Decorative Accessories", :owner => "Linens-N-Things", :level => 3)
        ThirdPartyCategory.create(:name => "Decorative Pillows", :parent => "Decorative Accessories", :owner => "Linens-N-Things", :level => 3)
      ThirdPartyCategory.create(:name => "Desks", :parent => "Furnishings", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Room Furnishings", :parent => "Furnishings", :owner => "Linens-N-Things", :level => 2)
        ThirdPartyCategory.create(:name => "Sports Rugs", :parent => "Room Furnishings", :owner => "Linens-N-Things", :level => 3)
        ThirdPartyCategory.create(:name => "Room Atomizers", :parent => "Room Furnishings", :owner => "Linens-N-Things", :level => 3)
        ThirdPartyCategory.create(:name => "Lamps", :parent => "Room Furnishings", :owner => "Linens-N-Things", :level => 3)
        ThirdPartyCategory.create(:name => "Windows", :parent => "Room Furnishings", :owner => "Linens-N-Things", :level => 3)
        ThirdPartyCategory.create(:name => "Area Rugs", :parent => "Room Furnishings", :owner => "Linens-N-Things", :level => 3)
        ThirdPartyCategory.create(:name => "Chairs", :parent => "Room Furnishings", :owner => "Linens-N-Things", :level => 3)
      ThirdPartyCategory.create(:name => "Slipcovers", :parent => "Furnishings", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Team Stuff", :parent => "Furnishings", :owner => "Linens-N-Things", :level => 2)
      
    ThirdPartyCategory.create(:name => "Kitchen", :parent => "", :owner => "Linens-N-Things", :level => 1)
      ThirdPartyCategory.create(:name => "Bakeware/Cookware", :parent => "Kitchen", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "BBQ/Grills", :parent => "Kitchen", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Dinnerware/Glassware", :parent => "Kitchen", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Food Storage", :parent => "Kitchen", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Kitchen Electrics", :parent => "Kitchen", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Kitchen Utensils", :parent => "Kitchen", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Water Filtration", :parent => "Kitchen", :owner => "Linens-N-Things", :level => 2)
      
    ThirdPartyCategory.create(:name => "School Supplies", :parent => "", :owner => "Linens-N-Things", :level => 1)
      ThirdPartyCategory.create(:name => "Tech accessories", :parent => "School Supplies", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Backpacks", :parent => "School Supplies", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Coolers", :parent => "School Supplies", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Lunchboxes", :parent => "School Supplies", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Message/Cork Boards", :parent => "School Supplies", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Survival Kits", :parent => "School Supplies", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Rolling Backpacks", :parent => "School Supplies", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Security", :parent => "School Supplies", :owner => "Linens-N-Things", :level => 2)
      
    ThirdPartyCategory.create(:name => "Storage & Organization", :parent => "", :owner => "Linens-N-Things", :level => 1)
      ThirdPartyCategory.create(:name => "Desk Storage", :parent => "Storage & Organization", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Bike Racks", :parent => "Storage & Organization", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Bins", :parent => "Storage & Organization", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Closet Storage", :parent => "Storage & Organization", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Food Storage", :parent => "Storage & Organization", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Hangers", :parent => "Storage & Organization", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Laundry", :parent => "Storage & Organization", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Locker Accessories", :parent => "Storage & Organization", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Locker Shelves", :parent => "Storage & Organization", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Luggage", :parent => "Storage & Organization", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Over the Door", :parent => "Storage & Organization", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Shoe Racks", :parent => "Storage & Organization", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Storage Boxes", :parent => "Storage & Organization", :owner => "Linens-N-Things", :level => 2)
      
    ThirdPartyCategory.create(:name => "Dorm Essentials", :parent => "", :owner => "Linens-N-Things", :level => 1)
    
    ThirdPartyCategory.create(:name => "Wall Art", :parent => "", :owner => "Linens-N-Things", :level => 1)
      ThirdPartyCategory.create(:name => "Hanging Accessories", :parent => "Wall Art", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Posters", :parent => "Wall Art", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Street Signs", :parent => "Wall Art", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Vinyl", :parent => "Wall Art", :owner => "Linens-N-Things", :level => 2)
        ThirdPartyCategory.create(:name => "Baby Kids", :parent => "Vinyl", :owner => "Linens-N-Things", :level => 3)
        ThirdPartyCategory.create(:name => "Fun", :parent => "Vinyl", :owner => "Linens-N-Things", :level => 3)
        ThirdPartyCategory.create(:name => "Home", :parent => "Vinyl", :owner => "Linens-N-Things", :level => 3)
        ThirdPartyCategory.create(:name => "Inspirational", :parent => "Vinyl", :owner => "Linens-N-Things", :level => 3)
      
    ThirdPartyCategory.create(:name => "Personal Care", :parent => "", :owner => "Linens-N-Things", :level => 1)
    
    ThirdPartyCategory.create(:name => "Tailgating", :parent => "", :owner => "Linens-N-Things", :level => 1)
      ThirdPartyCategory.create(:name => "BBQ Accessories", :parent => "Tailgating", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Tables", :parent => "Tailgating", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Coolers/Grills", :parent => "Tailgating", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Chairs", :parent => "Tailgating", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Stadium Cushons", :parent => "Tailgating", :owner => "Linens-N-Things", :level => 2)
      ThirdPartyCategory.create(:name => "Tailgating accessories", :parent => "Tailgating", :owner => "Linens-N-Things", :level => 2)
  end

  def self.down
    ThirdPartyCategory.delete_all
  end
end
