class PopulateStaesCountries < ActiveRecord::Migration
  def self.up
    Country.create(:id => 1, :country_name => 'United States', :abbreviation => 'US')
    Country.create(:id => 2, :country_name => 'Canada', :abbreviation => 'CA')
    
    State.create(:id => 1,  :full_name => 'Alabama',               :abbreviation => 'AL')
    State.create(:id => 2,  :full_name => 'Alaska',                :abbreviation => 'AK')
    State.create(:id => 3,  :full_name => 'Arizona',               :abbreviation => 'AZ')
    State.create(:id => 4,  :full_name => 'Arkansas',              :abbreviation => 'AR')
    State.create(:id => 5,  :full_name => 'California',            :abbreviation => 'CA')
    State.create(:id => 6,  :full_name => 'Colorado',              :abbreviation => 'CO')
    State.create(:id => 7,  :full_name => 'Connecticut',           :abbreviation => 'CT')
    State.create(:id => 8,  :full_name => 'Delaware',              :abbreviation => 'DE')
    State.create(:id => 9,  :full_name => 'District of Columbia', :abbreviation => 'DC')
    State.create(:id => 10, :full_name => 'Florida',               :abbreviation => 'FL')
    State.create(:id => 11, :full_name => 'Georgia',               :abbreviation => 'GA')
    State.create(:id => 12, :full_name => 'Hawaii',                :abbreviation => 'HI')
    State.create(:id => 13, :full_name => 'Idaho',                 :abbreviation => 'ID')
    State.create(:id => 14, :full_name => 'Illinois',              :abbreviation => 'IL')
    State.create(:id => 15, :full_name => 'Indiana',               :abbreviation => 'IN')
    State.create(:id => 16, :full_name => 'Iowa',                  :abbreviation => 'IA')
    State.create(:id => 17, :full_name => 'Kansas',                :abbreviation => 'KS')
    State.create(:id => 18, :full_name => 'Kentucky',              :abbreviation => 'KY')
    State.create(:id => 19, :full_name => 'Louisiana',             :abbreviation => 'LA')
    State.create(:id => 20, :full_name => 'Maine',                 :abbreviation => 'ME')
    State.create(:id => 21, :full_name => 'Maryland',              :abbreviation => 'MD')
    State.create(:id => 22, :full_name => 'Massachusetts',         :abbreviation => 'MA')
    State.create(:id => 23, :full_name => 'Michigan',              :abbreviation => 'MI')
    State.create(:id => 24, :full_name => 'Minnesota',             :abbreviation => 'MN')
    State.create(:id => 25, :full_name => 'Mississippi',           :abbreviation => 'MS')
    State.create(:id => 26, :full_name => 'Missouri',              :abbreviation => 'MO')
    State.create(:id => 27, :full_name => 'Montana',               :abbreviation => 'MT')
    State.create(:id => 28, :full_name => 'Nebraska',              :abbreviation => 'NE')
    State.create(:id => 29, :full_name => 'Nevada',                :abbreviation => 'NV')
    State.create(:id => 30, :full_name => 'New Hampshire',         :abbreviation => 'NH')
    State.create(:id => 31, :full_name => 'New Jersey',            :abbreviation => 'NJ')
    State.create(:id => 32, :full_name => 'New Mexico',            :abbreviation => 'NM')
    State.create(:id => 33, :full_name => 'New York',              :abbreviation => 'NY')
    State.create(:id => 34, :full_name => 'North Carolina',        :abbreviation => 'NC')
    State.create(:id => 35, :full_name => 'North Dakota',          :abbreviation => 'ND')
    State.create(:id => 36, :full_name => 'Ohio',                  :abbreviation => 'OH')
    State.create(:id => 37, :full_name => 'Oklahoma',              :abbreviation => 'OK')
    State.create(:id => 38, :full_name => 'Oregon',                :abbreviation => 'OR')
    State.create(:id => 39, :full_name => 'Pennsylvania',          :abbreviation => 'PA')
    State.create(:id => 40, :full_name => 'Rhode Island',          :abbreviation => 'RI')
    State.create(:id => 41, :full_name => 'South Carolina',        :abbreviation => 'SC')
    State.create(:id => 42, :full_name => 'South Dakota',          :abbreviation => 'SD')
    State.create(:id => 43, :full_name => 'Tennessee',             :abbreviation => 'TN')
    State.create(:id => 44, :full_name => 'Texas',                 :abbreviation => 'TX')
    State.create(:id => 45, :full_name => 'Utah',                  :abbreviation => 'UT')
    State.create(:id => 46, :full_name => 'Vermont',               :abbreviation => 'VT')
    State.create(:id => 47, :full_name => 'Virginia',              :abbreviation => 'VA')
    State.create(:id => 48, :full_name => 'Washington',            :abbreviation => 'WA')
    State.create(:id => 49, :full_name => 'West Virginia',         :abbreviation => 'WV')
    State.create(:id => 50, :full_name => 'Wisconsin',             :abbreviation => 'WI')
    State.create(:id => 51, :full_name => 'Wyoming',               :abbreviation => 'WY')
    
    State.create(:id => 52, :full_name => 'Alberta',               :abbreviation =>'AB')
    State.create(:id => 53, :full_name => 'British Columbia',      :abbreviation =>'BC')
    State.create(:id => 54, :full_name => 'Manitoba',              :abbreviation =>'MB')
    State.create(:id => 55, :full_name => 'New Brunswick',         :abbreviation =>'NB')
    State.create(:id => 56, :full_name => 'Newfoundland and Labrador', :abbreviation =>'NL')
    State.create(:id => 57, :full_name => 'Northwest Territories', :abbreviation =>'NT')
    State.create(:id => 58, :full_name => 'Nova Scotia',           :abbreviation =>'NS')
    State.create(:id => 59, :full_name => 'Nunavut',               :abbreviation =>'NU')
    State.create(:id => 60, :full_name => 'Ontario',               :abbreviation =>'ON')
    State.create(:id => 61, :full_name => 'Prince Edward Island',  :abbreviation =>'PE')
    State.create(:id => 62, :full_name => 'Quebec',                :abbreviation =>'QC')
    State.create(:id => 63, :full_name => 'Saskatchewan',          :abbreviation =>'SK')
    State.create(:id => 64, :full_name => 'Youkon',                :abbreviation =>'YT')
    
  end

  def self.down
    Country.delete_all
    State.delete_all
  end
end
